version: '3'
services:
  flask:
    build: docker/flask
    container_name: flask
    ports:
      - "5000:5000"  # Porta do Flask
    networks:
      - astro_default

networks:
  astro_default:
    driver: bridge