dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: projeto-lobobranco
      dataset: mercadolivre
      keyfile: /usr/local/airflow/dags/credentials/google_credential.json
      threads: 4